// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqxbwjgpzhnczeedkjyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxeGJ3amdwemhuY3plZWRranloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTkyMDAsImV4cCI6MjA3MDgzNTIwMH0.yPcRx3aDT4hWy0TBsa_qVRxgTttRGKOP-dcisg45564";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});